# Generated by Django 3.2.16 on 2022-10-12 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_bookinstance_wbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='wbook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.book'),
        ),
    ]
